services:
  backend:
    build: .
    ports:
      # Bind only to localhost for security. Use reverse proxy for external access
      - "127.0.0.1:8888:8888"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - ANTHROPIC_ADMIN_API_KEY=${ANTHROPIC_ADMIN_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_PAT=${GITHUB_PAT}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/.venv
    
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=ghost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD:-ghost_password}
    ports:
      # Only expose to localhost. Internal services use network
      - "127.0.0.1:5432:5432"
    expose:
      - "5432"  # Available to other containers on the network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    ports:
      # Only expose to localhost. Internal services use network  
      - "127.0.0.1:6379:6379"
    expose:
      - "6379"  # Available to other containers on the network
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
