apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: ghost-backend
  labels:
    app: redis
    app.kubernetes.io/name: ghost-backend
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
